### ISSUE TITLE
How to retreive Session information from OCPP Clients Requests?

### ISSUE THREAD

**Issue by vikram919** [ChargeTimeEU/Java-OCA-OCPP#102]
Given a charge box identity how can i retreive the session information/session id from connections existing? Why the api cannot provide session information for `SessionEvents` callback method `handleRequest`? 

The information of charge box identity besides session id in `handleRequest` callback will be sinful IMHO! :)

**Comment by TVolden** [comment]
Hi @vikram919,

The library does not retain the SessionInformation, which is transmitted along with the session Id when a new connection is established.
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/e8ef72491087c0b2b31d116d3bd7e00306a00145/ocpp-common/src/main/java/eu/chargetime/ocpp/ServerEvents.java#L32

I wanted to keep the abstraction level as low as possible, to give the implementer as many options as possible. I you would like to store the session information along with the session Id, then I would recommend a repository. Maybe something like this:
```java
interface ISessionRepository
{
  void StoreSession(UUID sessionId, SessionInformation information);
  SessionInformation GetBySessionId(UUID sessionId);
  void RemoveSession(UUID sessionId);
}
```

**Comment by vikram919** [comment]
Thanks for the explanation.
