### ISSUE TITLE
ocpp 1.6 - Cannot send TriggerMessageRequest to client

### ISSUE THREAD

**Issue by vikram919** [ChargeTimeEU/Java-OCA-OCPP#103]
Hi there!,

I am using OCPP 1.6 json server and am trying to send `TriggerMessageRequest` to the client given its sessionId, I see the server throws an `eu.chargetime.ocpp.UnsupportedFeatureException`. Why is it not supported? Can it be added?

````java
TriggerMessageRequest triggerMessageRequest = new TriggerMessageRequest(TriggerMessageRequestType.StatusNotification);
triggerMessageRequest.setConnectorId(1);
jsonServer.send(sessionIndex, triggerMessageRequest).whenComplete((confirmation, throwable) -> log.info("{}", confirmation));
````

Thanks!

**Comment by TVolden** [comment]
In order to send a request, you have to support the whole profile (by design):
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/e8ef72491087c0b2b31d116d3bd7e00306a00145/ocpp-common/src/main/java/eu/chargetime/ocpp/Server.java#L186

**Comment by TVolden** [comment]
The request is from this profile https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/master/ocpp-v1_6/src/main/java/eu/chargetime/ocpp/feature/profile/ServerRemoteTriggerProfile.java

**Comment by TVolden** [comment]
Use the addFeatureProfile method on the server to add the profile.
Hope it helps. Sorry for the many small replies, im writing then on my phone 🙂

**Comment by vikram919** [comment]
Awesome thanks! 👏
