### ISSUE TITLE
GetCompositeSchedule impmentation

### ISSUE THREAD

**Issue by artado** [ChargeTimeEU/Java-OCA-OCPP#104]
Hi,
Is GetCompositeSchedule from SmartCharging profile implemented? I cannot find it.

**Comment by TVolden** [comment]
Hi @artado,

Sorry for my slow reply.

You should be able to create a GetCompositeSchedule request via the SmartCharging server profile:
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/e8ef72491087c0b2b31d116d3bd7e00306a00145/ocpp-v1_6/src/main/java/eu/chargetime/ocpp/feature/profile/ServerSmartChargingProfile.java#L98-L100

Are you using the released version here on github?

**Comment by artado** [comment]
Hi Thomas, thanks for your response. Apologies, I can see now that it was added in one of the recent commits.
Another question related to that (let me know if you want me to open different issue):
I am using jitpack.io to compile builds, I was using https://jitpack.io/com/github/ChargeTimeEU/Java-OCA-OCPP/afbdbc9/build.log and it worked fine expect missing GetCompositeSchedule.
When I try to compile the newest one I get exceptions: https://jitpack.io/com/github/ChargeTimeEU/Java-OCA-OCPP/e8ef724/build.log

**Comment by TVolden** [comment]
It's okay. It looks like maven is complaining about using http, can I get you to change the build file to use https instead to see if that works:
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/e8ef72491087c0b2b31d116d3bd7e00306a00145/build.gradle#L29

**Comment by TVolden** [comment]
Heh, I just did it myself. Seems to work now:
https://jitpack.io/#ChargeTimeEU/Java-OCA-OCPP

**Comment by artado** [comment]
That is great, thanks for your help Thomas!

**Comment by artado** [comment]
Hi Thomas,

I think the build is still failing, do you have any ideas? https://jitpack.io/com/github/ChargeTimeEU/Java-OCA-OCPP/-29d21f7839-1/build.log

**Comment by TVolden** [comment]
Looks like a styling issue. I'll try to fix it quickly.

**Comment by TVolden** [comment]
Hopefully, it will work this time: https://jitpack.io/#ChargeTimeEU/Java-OCA-OCPP
