### ISSUE TITLE
bug: BootNotificationConfirmation does not accept interval=0

### ISSUE THREAD

**Issue by thetric** [ChargeTimeEU/Java-OCA-OCPP#105]
According to the OCPP 1.6 spec it should be allowed to specify interval=0:

> "If that interval value is zero, the Charge Point chooses a waiting interval on its own, in a way that avoids flooding the Central System with requests."
>
> --- Source: OCPP 1.6 spec, section 4.2. Boot Notification

**Comment by TVolden** [comment]
Hi @thetric,

Thanks for your input. As far as I can see the validation is the cause of the problem:
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/29d21f783921bb294230343dd20389a9bc25aa51/ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/core/BootNotificationConfirmation.java#L165

I'll make a fix.
