### ISSUE TITLE
GetCompositeScheduleRequest.validate() changingRateUnitType check

### ISSUE THREAD

**Issue by artado** [ChargeTimeEU/Java-OCA-OCPP#112]
GetCompositeScheduleRequest.validate() should not check for **changingRateUnitType** parameter as it is **optional**.

`  public boolean validate() {
    boolean valid = connectorId != null && connectorId >= 0;
    valid &= duration != null;
    valid &= changingRateUnitType != null;

    return valid;
  }
`

![image](https://user-images.githubusercontent.com/3541390/75609710-da5fe000-5b02-11ea-9433-581ae1d54a0a.png)

**Comment by TVolden** [comment]
Hi @artado ,

Thanks for reporting it. I'll make a fix for it by monday.
