### ISSUE TITLE
Do you consider deploying artifacts to maven central repository?

### ISSUE THREAD

**Issue by PiotrKowalskiV** [ChargeTimeEU/Java-OCA-OCPP#136]
Hello,

in my project I import your libraries as maven dependencies obviously. It would be convenient for users, if eu.chargetime.ocpp maven artifacts were present on maven central repository. At the moment I have to download source code and build it locally in order to have them in local maven repository, so that maven "sees" them. Not much hassle, but still.

Sincerely,
Piotr Kowalski

**Comment by sfeilmeier** [comment]
We do the same for OpenEMS: https://github.com/OpenEMS/openems/tree/develop/io.openems.wrapper.eu.chargetime.ocpp. 

Same here: not much hassle, but it would be convenient if we could just use a library from maven - ideally with OSGi headers included.

Thanks for the great library and all the effort!
Regards,
Stefan

**Comment by TVolden** [comment]
Hi,

Thanks for the enquiry. I have tried to publish the library a couple of times. I had it all set up, but hesitated to publish because the retry logic was faulty.

I'll put it on my todo list, but I can't promise that I'll get around to it before my exam period is over. Hope that's okay.

Sincerely,
Thomas Volden

**Comment by bantu** [comment]
Hello everyone.

I would appreciate if this issue could be addressed. Is there anything I can help with?

Thank you
Andreas

**Comment by TVolden** [comment]
Hi Bantu,

I'm really sorry for the inactivity, but my work load is too big for me to look into this at the moment. I'll address it after my exams.

I don't know much about deploying to maven central repo, so any help/resources would be greatly appreciated when the time comes.

Sincerely,
Thomas Volden

**Comment by TVolden** [comment]
Hi again,

It should be released to maven central repo now, although I think it takes some time to become publicly available.

<dependency>
  <groupId>eu.chargetime.ocpp</groupId>
  <artifactId>v1_6</artifactId>
  <version>1.0</version>
</dependency>

**Comment by bantu** [comment]
Hi @TVolden. Thanks for taking care of this. I see the `v1_6` on maven at https://search.maven.org/search?q=eu.chargetime.ocpp. However, the other artifacts (e.g. `OCPP-J` and `common`) are missing.

**Comment by TVolden** [comment]
Hi @bantu,

Thanks for your feedback. I'll try to fix it tomorrow.

Sincerely
Thomas

**Comment by TVolden** [comment]
Hi again,

I have given it some shot and I think it finally worked:
https://mvnrepository.com/artifact/eu.chargetime.ocpp

Sorry for the slow response, it takes 24 hours every time I tried a new attempt.

Sincerely,
Thomas

**Comment by bantu** [comment]
Hello.

Attempting to depend on `eu.chargetime.ocpp:v1_6:1.0` via gradle, I am seeing this:

```
* What went wrong:
Execution failed for task ':my-library:compileJava'.
> Could not resolve all files for configuration ':my-library:compileClasspath'.
   > Could not resolve eu.chargetime.ocpp:OCPP-J:1.0.
     Required by:
         project :my-library > eu.chargetime.ocpp:v1_6:1.0
      > Could not resolve eu.chargetime.ocpp:OCPP-J:1.0.
         > Could not parse POM https://repo.maven.apache.org/maven2/eu/chargetime/ocpp/OCPP-J/1.0/OCPP-J-1.0.pom
            > Could not find eu.chargetime.ocpp:all:1.0.
              Searched in the following locations:
                - https://repo.maven.apache.org/maven2/eu/chargetime/ocpp/all/1.0/all-1.0.pom
              If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
```

The OCPP 2.0 package seems to be missing too.

Thanks
