### ISSUE TITLE
Unable to Get Latest Library JAR Files

### ISSUE THREAD

**Issue by ioc-tanay** [ChargeTimeEU/Java-OCA-OCPP#138]
Hi, 

First of all, thank you for this library and the amount of effort you have put into this.

I am new to OCPP and want to implement a server for my company's new product. However, I am unable to get the latest JAR files using either of the two methods mentioned in the Wiki/Issues - 

1. I have tried using JitPack through Maven, and even though it does add the dependencies successfully, it only imports v0.3 which is 286 commits behind the Master branch and is quite outdated. **Can you please add the latest versions to the Releases so that we can directly get the JAR files from there?**
2. I also tried running `mvn install` on the project's root directory but it is unable to install successfully and runs into multiple errors that I cannot seem to figure out. Here is one of the main ones that I see: "[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project common: MavenReportException: Error while creating archive: [ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/7/docs/api/ are in the unnamed module." Can you help me debug this so I can get the latest JAR files (v0.5) and implement the server?

Looking forward to your reply. Best regards!

**Comment by TVolden** [comment]
Hi @ioc-tanay,

Sorry for my slow response.

I didn't actually add those releases to jitpack. I'm guessing "they" took them from github releases.
You can use the master snapshot if your looking for something fresh: https://jitpack.io/#ChargeTimeEU/Java-OCA-OCPP/master-SNAPSHOT

The error you get is related to the automatically generated java docs, weirdly enough I don't get them. Try `mvn install -Dmaven.javadoc.skip=true`

**Comment by ioc-tanay** [comment]
Thank you for responding!

Got it. I didn't mean adding releases to JitPack but rather to GitHub itself.

Thanks, I was able to fix it and get the latest JAR files. It seems to be an issue when you are not using Java 8 (I have JDK 14 installed) and can also be fixed by adding a <source> tag in the java docs configuration.

Cheers!

**Comment by TVolden** [comment]
Hi @ioc-tanay,

I'm going to close this, since you found a solution.
