### ISSUE TITLE
how to add Temperture to MeterValues ? 

### ISSUE THREAD

**Issue by SmartTransp** [ChargeTimeEU/Java-OCA-OCPP#141]
I want to change the default meter values been send from the charger 
so it will send me also the temperture and not just the default
{"key":"MeterValuesSampledData","value":"Current.Import,Energy.Active.Import.Register,Power.Active.Import,SoC,Voltage"}

what is the correct why to do this ?

Thanks ,

**Comment by robert-s-ubi** [comment]
You send a ChangeConfiguration.req with key "MeterValuesSampledData" and value "Temperature" (or "Current.Import,Energy.Active.Import.Register,Power.Active.Import,SoC,Temperature,Voltage" if you wish to keep receiving the default sampled values).

Note that the Charging Station may respond with "Rejected" if it does not support the requested measurand(s).

**Comment by TVolden** [comment]
Thanks @robert-s-ubi for helping out.

@SmartTransp did @robert-s-ubi reply, solve your problem? If so, can I get you to close the issue?

**Comment by TVolden** [comment]
I assume it's fixed. Otherwise please ask questions in the discussion section.
