### ISSUE TITLE
Adjust README of repo

### ISSUE THREAD

**Issue by MauroBono** [ChargeTimeEU/Java-OCA-OCPP#161]
I had some struggles getting to the maven repository here: https://mvnrepository.com/artifact/eu.chargetime.ocpp
since it was just mentioned in a seperate issue on the project plan (https://tree.taiga.io/project/tvolden-java-oca-ocpp/issue/136).

Maybe you can just insert the link to the maven repo somewhere in the README for clearer and more easy use, since it would be visible on the first sight

**Comment by TVolden** [comment]
Hi @MauroBono,

Thanks, I'll do that.

**Comment by TVolden** [comment]
Thanks again for the input, I'm going to close this. :)
