### ISSUE TITLE
Problems with OCPP1.6J client implementation

### ISSUE THREAD

**Issue by kandangit** [ChargeTimeEU/Java-OCA-OCPP#164]
Hello, 

We have upgraded our custom Central system implementation to use OCPP1.6J

We  successfully implemented server side with the library but the client side is not working when we call the charge post fro our central system. We use the same  code as in the sample (https://github.com/ChargeTimeEU/Java-OCA-OCPP/wiki/Setting-up-v1.6-OCPP-J-client)

**whenComplete returns**:

`eu.chargetime.ocpp.CallErrorException: errorCode='Not connected', errorDescription='The request can't be sent due to the lack of connection', payload=RemoteStartTransactionRequest{connectorId=90000007, idTag=FF000005, chargingProfile=null, isValid=true}`

We call:

`client.connect("http://localhost:38080/chargepostsws/ocpp1_6/IGCTM00005", null);
`

The URL is of a mocked websocket server (to simulate the charge post response). It is implemented in JavaEE and deployed in Wildfly. Actually, the method @OnOpen of the class annotated with @ServerEndpoint is executed but the  @OnClose method is inmediately called. 

For now we call the mocked server with JavaEE and have no connection problems. We have this code in case it helps (Is what we will do as an alternative):

```
// cardRfid, idConnector parameters sent from the application
RemoteStartTransactionRequest payload = new RemoteStartTransactionRequest(cardRfid);
payload.setConnectorId(Integer.parseInt(idConnector));

String uniqueId = UUID.randomUUID().toString();
String message = String.format("[2,\"%s\",\"%s\",%s]", uniqueId, "RemoteStartTransaction", payload);

MockedClientEndpoint client = new MockedClientEndpoint(new URI("http://localhost:38080/chargepostsws/ocpp1_6/IGCTM00005"));

MockedClientEndpoint.latch = new CountDownLatch(1); // Just to synchronously wait
// Calls @OnMessage method which sends message to http://localhost:38080/chargepostsws/ocpp1_6/IGCTM00005
client.sendMessage(message);  
// We wait for response (method @OnMessage of MockedClientEndpoint)
MockedClientEndpoint.latch.await(1, TimeUnit.MINUTES);

String response = clientEndPoint.getResponse();
```

**What is the reason of this disconnection? Could it be that internally the library won't understand the http protocol?**

### A quick question about the JSON client sample 
(https://github.com/ChargeTimeEU/Java-OCA-OCPP/wiki/Setting-up-v1.6-OCPP-J-client)

It sends a BootNotification but this is a server operation (ie from charge post to the central system). Is it correct? I would have expected a RemoteStartTransactionRequest for example. May not have much effect may look confusing.

I read the code as is the best documentation. Apologies for any misunderstanding of the library itself.

**Comment by jmluy** [comment]
Regarding the sample, boot notification is correct, it's from chargepoint (client) to the central system (server). Remote start is from central (server) to the chargepoint (client).

From what I understood, you are trying to connect from your central system to the chargepoint and sending a remote start? You don't need to connect as client. When you started your server, you were probably using something like
`server = new JSONServer(new ServerCoreProfile(coreProfileHandler))`
You can just use the _server_ object and call `server.send(UUID session, Request request)` where _request_ is **_RemoteStartTransactionRequest_**

**Comment by kandangit** [comment]
Thanks for clarification, I misunderstood part of the example of the documentation.

Yes, indeed on startup of the J2EE container we start up the websocket server with that code. That server is continuosly listening for calls coming the charge posts (BootNotification, etc) to our localhost:8887 URL 

But how to open a new connection from Central System to the Charge Post to send that RemoteStartTransactionRequest?

To explain a bit: From an admin page we request actions on the post and all we do (at the moment without the library) is starting a "new" socket connection against the websocket URL of the charge post (which we have stored in the DB), sending the request and waiting for the response. 

With:
`server.send(UUID session, Request request)`

How do I create a new session for this communication? The server is already started in localhost:8887 URL which is different from the post URL.

**Comment by jmluy** [comment]
With the library, you don't need to start a new session. When your chargepoint connects to the server, the server maintains the session. You just need to call the server function to send the remote start and it will use the existing connection to your chargepoint.

**Comment by kandangit** [comment]
Right, that is now clear. I assumed a new session is opened every time you communicate with the device. Apologies for my misunderstanding! We will store the Session UUID and reuse it in any further operation CentralSystem -> Device.
