### ISSUE TITLE
SOAP Message element order is different with OCA OCPP_CentralSystemService_1.6.wsdl

### ISSUE THREAD

**Issue by foluswen** [ChargeTimeEU/Java-OCA-OCPP#17]
Hello

     I use your library to test with OCA testing tools face some issue and share to you.

     SOAP message element order doesn't same as OCPP_CentralSystemService_1.6.wsdl

     We must set element order in model file

     for example:
`@XmlRootElement
@XmlType(propOrder = { "connectorId", "status", "errorCode", "info", "timestamp", "vendorId", "vendorErrorCode"})

public class StatusNotificationRequest implements Request {}`

**Comment by TVolden** [comment]
Hi there,

Thanks for your input, I'll investigate it right away.

**Comment by TVolden** [comment]
98ecf32a564eef20aacf4a0da5d9634fe7d49be9 Added a fix that should solve it.

**Comment by foluswen** [comment]
package-info.java also have some issue, namespace should equal "urn://Ocpp/Cs/2015/10/"


`@XmlSchema(namespace = "urn://Ocpp/Cp/2015/10", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.chargetime.ocpp.model.core;`

**Comment by foluswen** [comment]
Besides , data model about comfirmation doesn't match wsdl describe

Code shoulde fix as bolow (example):

wdsl description is `<s:element name="bootNotificationResponse" type="tns:BootNotificationResponse"/>`

`@XmlRootElement(name ="bootNotificationResponse")`
`@XmlType(propOrder = { "status", "currentTime", "interval"})`
`public class BootNotificationConfirmation implements Confirmation`

**Comment by TVolden** [comment]
So it has to say /Cs/ instead of /Cp/ ?

**Comment by foluswen** [comment]
yes

original code is `urn://Ocpp/Cp/2015/10`

correct should `urn://Ocpp/Cs/2015/10/`

**Comment by TVolden** [comment]
Okay, thanks. I'll look into it later today.

**Comment by TVolden** [comment]
Okay, I added the specific names for the confirmation classes and changed the namespace. d7577fc7f7397eae99d0f2f7a6c1c345ba03a109
Please check if that has solved the issue

**Comment by foluswen** [comment]
Thank you.
