### ISSUE TITLE
SOAPSyncHelper.java issue

### ISSUE THREAD

**Issue by foluswen** [ChargeTimeEU/Java-OCA-OCPP#19]
I test some profile send from server to chargerbox by OCA testing tooling, chargerbox occur cannot reply message to server.

There maybe is a bug in SOAPSyncHelper.java, because of call forwardMessage() too early and cause 'uniqueID' does not put into 'promises'.

I move forwardMessage() to last section, and solve the issue.

`public CompletableFuture<SOAPMessage> relay(SOAPMessage message) {`
`        forwardMessage(message);<============================ position must move to last`
`        CompletableFuture<SOAPMessage> promise = null;`
`        String uniqueID = getHeaderValue(message, "MessageID");`
`        if (uniqueID != null) {`
`            promise = new CompletableFuture<>();`
`            promises.put(uniqueID, promise);`
`        }`
`         <============================================= move to here`
`        return promise;`
`    }`

**Comment by TVolden** [comment]
Hi,

I really appreciate all your valuable feedback.
I'll look into it.

**Comment by TVolden** [comment]
b6b55dadb1472b8f3523472ac98f2ee4ec682c96
I have moved the call as you suggested, tests passes (ignore the unstable integration test :P ) please check if it works.

**Comment by foluswen** [comment]
OK thank you
