### ISSUE TITLE
How does the server receive and process the client's response

### ISSUE THREAD

**Issue by broce-597** [ChargeTimeEU/Java-OCA-OCPP#199]
After the server sends the request (RemoteStopTransactionRequest), the client will return the data, where does the server receive the data returned by the client, I did not locate the code logic, it may be my problem, please help me。

**Comment by TVolden** [comment]
Hi @broce-597 ,

Thank you for the question. The response should be returned from the send method. To prevent a blocking call however, I use a build in java class to handle future promise. There should be a whenComplete method to call back once the client had responded. 

Please see https://github.com/ChargeTimeEU/Java-OCA-OCPP/wiki/Setting-up-v1.6-OCPP-S-client for an example of the send->receive mechanic

**Comment by broce-597** [comment]
@TVolden Your answer solved my problem ，thanks！
