### ISSUE TITLE
Unit tests localisation problem

### ISSUE THREAD

**Issue by Staskkk** [ChargeTimeEU/Java-OCA-OCPP#20]
Hello,
Some unit tests (with double values, сomma instead of dot) for v1.6 failed, if your locale is not English.

**Comment by TVolden** [comment]
Hi,

Thanks for your feedback. I would like to help you, but how can I reproduce the problem? Can you provide some examples?

- Thomas

**Comment by TVolden** [comment]
I think I found the tests you mentioned. I'll have a fix for it with next commitment.

**Comment by goRaspy** [comment]
I just suceed to compile with mavem and set my locale to english. Tks :)

For now, I do not know what to do. I have a manifest error when I try to run jar targets.

**Comment by TVolden** [comment]
Interesting. How did you set locale to English?

Could you elaborate on the error you get? What did you try, please include examples so I can try it too. Also I would appreciate any error output.

Thanks

**Comment by goRaspy** [comment]
I was on windows. And I changed the locale by control panel (https://www.java.com/en/download/help/locale.xml ).

I did not saved logs before locale change. I will do it again this afternoon.

Concerning my error. After compiling I tried to run all generated jar file (v1_6-test-0.3.jar ; v1_6-0.3-javadoc.jar; common-0.3-javadoc.jar ; common-0.3.jar ; v1_6-0.3-sources.jar ; v1_6-0.3.jar : common-0.3-sources.jar) with java -jar xxx.jar but I allways get : “no main manifest attribute” error

Cheers

**Comment by goRaspy** [comment]
[logsMAVEM.txt](https://github.com/ChargeTimeEU/Java-OCA-OCPP/files/1049598/logsMAVEM.txt)

Attached filed is logs for mavem with "not english" locale

**Comment by TVolden** [comment]
Ah okay, now I get it. You can't really run it out of the box. It's a library so it actually doesn't have a main() method.

I can help you build a little program to run with. You can also try to play around with the example code, which I have attached.

**Comment by goRaspy** [comment]
Ok I understand,

Where can I find the example please ? I would love an example to run a JSON 1.6 endpoint like CPMS.

**Comment by TVolden** [comment]
There is an example for server and one for client:
Server: 
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/master/ocpp-v1_6-example/src/main/core_features/JSONServerSample.java

Client: 
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/master/ocpp-v1_6-example/src/main/core_features/JSONClientSample.java

**Comment by goRaspy** [comment]
I tried without sucess to build a main for examples :( 

I am not experimented at java. Any help welcome.

**Comment by TVolden** [comment]
I can write a quick client program to send commands, would that help?

I hope you understand, that you would have to write allot of java code to build a full blown client or server on this library.

**Comment by TVolden** [comment]
@Staskkk 
This hotfix should fix the issue: a7fbb56ea4fb67892098b1b3ecbc001665a751fc
Tested on a danish machine. Please verify and close.

**Comment by goRaspy** [comment]
Concerning the quick client, it should be very helpful.

My objective is not to build a complete CPMS but triing to interface (market) charging station with PV central using OCPP 1.6 charging profile.

**Comment by TVolden** [comment]
I'll create a small program for it. But that's off topic, this issue is solved.
