### ISSUE TITLE
Upgrade Java-Websocket dependency to 1.5.3

### ISSUE THREAD

**Issue by m-oben** [ChargeTimeEU/Java-OCA-OCPP#203]
Version 1.5.3 of the Java-Websocket library has been released a while ago and fixed a few issues. Currently version 1.5.2 is in use so we can upgrade.

Release notes: https://github.com/TooTallNate/Java-WebSocket/blob/master/CHANGELOG.md#version-release-153-20220409

**Comment by gvtelio** [comment]
@TVolden  Would you please also release a newer version to Maven repo? Thanks in advance.

**Comment by TVolden** [comment]
@gvtelio I have to add it to my to-do list. Hopefully I will have time next week.

**Comment by TVolden** [comment]
@gvtelio I have to add it to my to-do list. Hopefully I will have time next week.
