### ISSUE TITLE
To obtain sessionId, sessions map is sought for value

### ISSUE THREAD

**Issue by dimaa6** [ChargeTimeEU/Java-OCA-OCPP#208]
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/5c608f867defb5b5cc3d55fd7c55e8246f632f74/ocpp-common/src/main/java/eu/chargetime/ocpp/Server.java#L174

This happens each time request is received. Server may be handling hundreds of thousands of connections, with hundreds of requests coming in every second. Synthetic test with map having 100,000 `UUID` keys pointing to `String` values and 1000 `containsValue` calls took 4 seconds. Test with the same map and 1000 `containsKey` calls took only 0.1ms. This shows that `containsValue` method does not utilize `Map`'s ability to quickly find an object, instead, it iterates through all the values in regular scanning loop. If we really need to check if session is still present, we need to have `Set` of sessions in addition to the `Map`, and handle them together in atomic (synchronized) way - when adding a session, add it to both `Map` and `Set`, same when removing. Then `Set` will be used to quickly check if the session is still active.

**Comment by TVolden** [comment]
Hi @dimaa6,

Thank you for reaching out. I'm happy to hear that business is good.

You are right of cause, it's a waste of resources to use containsValue. Especially if the UUID is already stored in the session via the getSessionId method. 

Can I get you to create a PR for the change?

Sincerely
Thomas Volden

**Comment by dimaa6** [comment]
Sure, will do tomorrow.
