### ISSUE TITLE
Word "occurrence" is misspelled

### ISSUE THREAD

**Issue by dimaa6** [ChargeTimeEU/Java-OCA-OCPP#216]
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/9fe3b7910a15158686887530f09d3d8983ed9c16/ocpp-common/src/main/java/eu/chargetime/ocpp/Session.java#L159-L160

https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/9fe3b7910a15158686887530f09d3d8983ed9c16/ocpp-common/src/main/java/eu/chargetime/ocpp/OccurenceConstraintException.java#L28

Word occurrence is spelled with double R. This typo is visible not only at source code level, but is sent to the client (see first code snippet). I can fix it, should I do that?

**Comment by TVolden** [comment]
Hi @dimaa6,

God catch. I wouldn't be surprised if there were more. ;)
Just go ahead and make a PR and I'll merge it in.

Thanks you for keeping an eye on the code.

- Thomas

**Comment by mmauksch** [comment]
Considering a pull request fixing this got merged into v2 i would suggest to close this issue :)
