### ISSUE TITLE
BootNotificationRequest::setChargeBoxSerialNumber(null) throws NullPointerException

### ISSUE THREAD

**Issue by bantu** [ChargeTimeEU/Java-OCA-OCPP#221]
I am not sure whether this is the expected behavior, I do not believe it is.
```
new BootNotificationRequest().setChargeBoxSerialNumber(null);
```
throws a `NullPointerException` due to `.length()` in
```
    if (!ModelUtil.validate(chargeBoxSerialNumber, STRING_25_CHAR_MAX_LENGTH)) {
      throw new PropertyConstraintException(
          chargeBoxSerialNumber.length(), validationErrorMessage(STRING_25_CHAR_MAX_LENGTH));
    }
```
being called on a `null` `String`.

Note that `chargeBoxSerialNumber` is optional in `BootNotificationRequest`.

Here's a test for reproduction:
```
package eu.chargetime.ocpp.model.core.test;

import eu.chargetime.ocpp.model.core.BootNotificationRequest;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class BootNotificationRequestTest {

  @Rule public ExpectedException thrownException = ExpectedException.none();

  private BootNotificationRequest request;

  @Before
  public void setup() {
    request = new BootNotificationRequest();
  }

  @Test()
  public void validate_setChargeBoxSerialNumber_onNull_doesNotThrowNPE() {
    request.setChargeBoxSerialNumber(null);
  }
}
```

**Comment by bantu** [comment]
Created a branch with the test here: https://github.com/ChargeTimeEU/Java-OCA-OCPP/compare/master...bantu:Java-OCA-OCPP:test-for-github-221?expand=1

**Comment by TVolden** [comment]
Hi @bantu,

Your right, that makes no sense. Thanks for pointing it out.
Maybe the ModelUtil should have a small method to extract lengths or 0 from a string?

If you make a PR, I'll merge it ;)

- Thomas

**Comment by jmluy** [comment]
This also affects the other optional fields in that class like chargePointSerial;Number, firmwareVersion, iccid, imsi, meterSerialNumber and meterType.

**Comment by bantu** [comment]
> This also affects the other optional fields in that class like chargePointSerial;Number, firmwareVersion, iccid, imsi, meterSerialNumber and meterType.

Yes. Thank you. I was about to mention that. Does it also affect other classes?

**Comment by jmluy** [comment]
> > This also affects the other optional fields in that class like chargePointSerial;Number, firmwareVersion, iccid, imsi, meterSerialNumber and meterType.
> 
> Yes. Thank you. I was about to mention that. Does it also affect other classes?

I didn't check all but for some classes they do a check with something like the following.
```if (field != null && ...) ```

I saw some code which probably have the same issue

-  https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/1c53b530a7609c0c98edb98e87c214d8d5e187d7/ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/core/DataTransferRequest.java#L110-L116
- https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/1c53b530a7609c0c98edb98e87c214d8d5e187d7/ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/core/GetConfigurationRequest.java#L65-L71

**Comment by bantu** [comment]
@jmluy I'll focus on BootNotificationRequest.
