### ISSUE TITLE
How to customize the time format for json serialization

### ISSUE THREAD

**Issue by odiwml147** [ChargeTimeEU/Java-OCA-OCPP#222]

**Comment by jmluy** [comment]
@odiwml147 do you mean writing existing objects in this project to JSON and converting the time to a specific format?

**Comment by odiwml147** [comment]
> @odiwml147 do you mean writing existing objects in this project to JSON and converting the time to a specific format?

Yes. For example, MeterValues.req, I want to customize the json format.

**Comment by jmluy** [comment]
> > @odiwml147 do you mean writing existing objects in this project to JSON and converting the time to a specific format?
> 
> Yes. For example, MeterValues.req, I want to customize the json format.

It sounds like it's not something specific to this project and you can use something like Jackson and specify the format there?

**Comment by odiwml147** [comment]
> 
Thanks.OCPP Server supports the time string in ISO_ZONED_DATE_TIME format,can carry time zone information.This has solved my problem.But,OCPP Client only supports the time string in ISO_INSTANT format,it's just inconvenient to debug
