### ISSUE TITLE
"completedHandler": null in JSON objects

### ISSUE THREAD

**Issue by bantu** [ChargeTimeEU/Java-OCA-OCPP#224]
I am seeing `"completedHandler": null` in JSON strings. I don't think that's the expected behavior. I believe completedHandler must be prevented from being serialized.

**Comment by TVolden** [comment]
This may be related to PR #210 . @emilm can you investigate?

**Comment by bantu** [comment]
Yes, that should be related.

**Comment by emilm** [comment]
There was another discussion about this.
I had     private transient ConfirmationCompletedHandler completedHandler; which worked for me .
https://github.com/emilm/Java-OCA-OCPP/blob/f4b4f47881fd5d9fa291f254744d459424093e9a/ocpp-common/src/main/java/eu/chargetime/ocpp/model/Confirmation.java#L33

 But there was someone with a SOAP handler where you had to add another decorator:

https://github.com/ChargeTimeEU/Java-OCA-OCPP/pull/214/commits/cb92d044c0f0470faa4c58988e389eed6cead0ce

Are you saying there has to be additional decorators?

**Comment by bantu** [comment]
@emilm Thanks a lot for researching. It turns out I was accidentally using Jackson to serialize the object and Jackson was not configured to ignore XmlTransient. Hence, I believe this is not an issue of this library.

**Comment by emilm** [comment]
Great! Glad you found out, and relieved that it wasn't my fault :)
