### ISSUE TITLE
Can't handle handleDataTransferRequest and handleMeterValuesRequest 

### ISSUE THREAD

**Issue by kassymbekoff** [ChargeTimeEU/Java-OCA-OCPP#228]
Hello!
I use your example code for server app. Connection to charge station is ok. I can handle all requests, except handleMeterValuesRequest and handleMeterValuesRequest. Station doesn't send me request to this handlers.
Do I need to add some params or some settings on the server side? Or maybe I should enable some settings on station?

**Comment by aulianapip** [comment]
you should start charging process to get MeterValuesRequest from charging station or maybe you can send TriggerMessage with requestMessage "MeterValues" to get MeterValuesRequest

**Comment by kassymbekoff** [comment]
how to send TriggerMessage? Is there any documentation about this request ?

**Comment by aulianapip** [comment]
yes of course there is a document, you can go to the website https://www.openchargealliance.org/ and download the ocpp guide document

**Comment by kassymbekoff** [comment]
Thank you for response
