### ISSUE TITLE
Running basic client server class

### ISSUE THREAD

**Issue by Dharam625** [ChargeTimeEU/Java-OCA-OCPP#23]
Hi,

I have just started exploring this code. I want to run client server classes. However as they don't have main method I am unable to run. I am not sure what is the starting point. All I want to do is I want to establish connection between client and server.

Any help or hint would be big help.

**Comment by TVolden** [comment]
Hi there,

Thank you for reaching out. It's always nice to hear from people using the code. :)
The goal for this project is to create a library that can easily be adopted by equipment and operators. I'm leaving the application scope for them to implement (the way they see fit). This is the reason you won't find any main().

This means that if you would like to use the code, then you would have to create an application for it.
I have made a little start guide in the wiki: https://github.com/ChargeTimeEU/Java-OCA-OCPP/wiki/Getting-started
I would love to improve it, so any feedback to this would be greatly appreciated.

If you just need something quick and dirty, then try looking at the fake server/client I have made for the integration tests: https://github.com/ChargeTimeEU/Java-OCA-OCPP/tree/master/ocpp-v1_6-test/src/main/java/eu/chargetime/ocpp/test

In related news, I have received several requests for this, so I have decided to start a small experimental application. It's still really early but I'll publish it on github soon.

**Comment by TVolden** [comment]
I have whipped my experimental application together, so you can have a look:
https://github.com/ChargeTimeEU/ChargeTime-HQ

Please remember it still needs allot of work.

**Comment by goRaspy** [comment]
♥️

**Comment by Dharam625** [comment]
Thank you so much for quick reply. I will play around.
