### ISSUE TITLE
Renaming namespace for ocpp2 classes to allow usage of both Clients in the same project

### ISSUE THREAD

**Issue by mmauksch** [ChargeTimeEU/Java-OCA-OCPP#234]
Situation: Currently it is not possible to use the OCPP2 and OCPP1.6 Client in the same project because it will lead to a namespace clash ( both Versions define the IClientApi interface and implement it in JSONClient in the package eu.chargetime.ocpp )
Proposed solution: Move the ocpp2 classes to the eu.chargetime.ocpp2 namespace. This way the namespace clash would be resolved.

This issue was already raised by me in the gitter chat[1] and I will provide a pull request referencing this issue in a moment.
[1] https://matrix.to/#/!NqEtydRUbKNeWvNHlv:gitter.im/$hZYh1jgehVNGQqLaeWJxZU2h1LmCqbHu1HnpaledncA?via=gitter.im&via=matrix.org

**Comment by TVolden** [comment]
Hi @mmauksch,

Now that the namespace has been renamed, can I get you to verify that a client can in fact run both version?

If so, good work, and please close this issue. :)

- Thomas

**Comment by mmauksch** [comment]
Sorry i did not write a response to that ticket. My Client that uses the lib can have both dependencies active without conflicts.
Considering ubitricity has a large pull request for ocpp2 open i guess this and my private stuff i wanted to push back for ocpp2 will be moot in the near future anyways ;D
