### ISSUE TITLE
Ocpp1.6 soap request to central system

### ISSUE THREAD

**Issue by lahnaoja** [ChargeTimeEU/Java-OCA-OCPP#29]
Hi one and all,

After a small testing with a mock-up soap (xml) request (from pole to CentralSystem) I noticed that I’m not quite sure what’s the correct form of an Ocpp1.6 soap request. Especially how the soap headers and namespaces should be set. I think that the request below is close the right form, but, do you have any comments?

Of course it could be also so that implementations in the poles could differ slightly.
In case message form below is about the right one the library needs a little fix to handle it, I could make a PR for that.

B.r. Antti

```
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:ns="urn://Ocpp/Cs/2015/10/">
   <soap:Header xmlns:wsa="http://www.w3.org/2005/08/addressing">
      <ns:chargeBoxIdentity>Pole1000</ns:chargeBoxIdentity>
      <wsa:MessageID>1001001</wsa:MessageID>
      <wsa:From><wsa:Address>http://localhost:12345</wsa:Address></wsa:From>
      <wsa:ReplyTo><wsa:Address>http://www.w3.org/2005/08/addressing/anonymous</wsa:Address></wsa:ReplyTo>
      <wsa:To>http://localhost:8887</wsa:To>
      <wsa:Action>/Authorize</wsa:Action>
   </soap:Header>
   <soap:Body>
      <ns:authorizeRequest>
        <ns:idTag>tag200</ns:idTag>
      </ns:authorizeRequest>
   </soap:Body>
</soap:Envelope>
```

**Comment by TVolden** [comment]
Hi Antti,

Thanks for your feedback and PR. I'll probably won't have time to look into it before tomorrow. I have had some issues with the soap namespace especially because I have to change it based on wether it's a client or server call. It caused me some trouble back then, so I wouldn't be surprised if I got it wrong. 

Thomas

**Comment by lahnaoja** [comment]
Hi Thomas,
Thanks for the feedback, I guess it would be useful for the specification to have example request/responses...
B.r. Antti

**Comment by TVolden** [comment]
OCA has a test tool, which tests this. I have made changes to the soap namespace based on this tool:
https://github.com/ChargeTimeEU/Java-OCA-OCPP/issues/17

**Comment by TVolden** [comment]
Did I totally get you wrong? Did you mean the prefix ns for the elements?

**Comment by lahnaoja** [comment]
There has been some namespace prefix in the examples I have seen. So it could be "ns" (for responses). This prefix depends on how the namespace has been defined with xmlns in the xml, so I quess it depends on the implementation.
I think that in practice when receiving requests it's just enough to get the value of element regardless of namespace, as there hardly is any overlapping names in the ocpp request.

**Comment by TVolden** [comment]
If there is no overlap, then it shouldn't make a difference if the elements are prefixed with namespaces or not. If your charge equipment is complaining, then we'll add it in the lib, no problem.
The PR is pending, since there is a unit test failing (it's probably a dumb unit test that string compares the xml output, so I don't mind if you remove the test to fix the problem). Once everything builds and the unit tests are green, I can accept the PR.

**Comment by lahnaoja** [comment]
Hmmm. After a closer look and little more fix both, with prefix and without (default namespace), are now fine, and also the authorize request above goes through. PR modified. Should be fine now from functionality perspective?
In the PR there is also fix to get the pole's ocpp server address from soap header.

I could take a look to tests in case this otherwise looks fine.

Without the fix in the PR I got this reply:
```
<env:Code>
      <env:Value>env:Receiver</env:Value>
          <env:Subcode>
               <env:Value xmlns:ns1="urn://Ocpp/Cp/2015/10">ns1:OccurenceConstraintViolation</env:Value>
                </env:Subcode>
            </env:Code>
            <env:Reason>
                <env:Text xml:lang="en-US">Payload for Action is syntactically correct but at least one of the fields violates occurence constraints</env:Text>
            </env:Reason>
```

**Comment by TVolden** [comment]
It's wierd how I forgot to add the SOAP header information in e0a56cd83f7abbe01bd311e7c239c3697e8299b4 shame on me.

**Comment by lahnaoja** [comment]
Unit test should be fine now.

**Comment by TVolden** [comment]
I accepted it, please close the issue when you have tested it.

**Comment by lahnaoja** [comment]
Ok, thanks.
