### ISSUE TITLE
Possible leak in WebSocketListener

### ISSUE THREAD

**Issue by emilm** [ChargeTimeEU/Java-OCA-OCPP#5]
In WebSocketListener the 
`private HashMap<WebSocket, WebSocketReceiver> sockets;`
Is not removed from if you lose a connection / disconnect.

`@Override
public void onClose(WebSocket webSocket, int i, String s, boolean b) {
    sockets.get(webSocket).disconnect();
}` should remove it from the map. Maybe also check it for every connect unless you missed something? :)

**Comment by TVolden** [comment]
Thanks for your input.

I have cheated and made a fix the problem already (in response to the emails you sent). It's delivered with the latest push on the SOAP feature.

**Comment by emilm** [comment]
Great!
