### ISSUE TITLE
Unique session?

### ISSUE THREAD

**Issue by emilm** [ChargeTimeEU/Java-OCA-OCPP#6]
Since chargers can connect and disconnect etc, maybe it's a better idea to have a GUID instead of int for a session so there's no way you can confuse them?

**Comment by TVolden** [comment]
That's an excellent idea. Should it be an guid object or a string?

**Comment by TVolden** [comment]
I went with UUID based on this discussion: http://stackoverflow.com/questions/24887825/hashmap-uuid-or-string-as-key

**Comment by emilm** [comment]
Sorry for not answering! Yeah I supposed a pure uuid type is good.  Both string and uuid needs to do an equals anyway. I guess uuid is not a value type?

**Comment by TVolden** [comment]
the UUID object should be perfectly safe: http://stackoverflow.com/questions/30312867/java-is-it-safe-to-do-deepcopy-of-uuid-field-as-this-uuid-original-getuuid

I have set up a bidirectional hash map (thanks google) with the UUID as key.

**Comment by emilm** [comment]
Great :)

**Comment by TVolden** [comment]
Okay, the changes is pushed in commit 8ab84a280b2e53c3d5c6255d8e71994643b78d91

**Comment by emilm** [comment]
Thanks! why did you need the bimap? I will run on an embedded system so need to keep the amount of dependencies and code etc low. :)

**Comment by TVolden** [comment]
Mostly because of performance. I could experiment with a HashMap using a lambda expression instead.

**Comment by emilm** [comment]
Performance is #1 so that's great. Will test it now!

**Comment by TVolden** [comment]
Cool, let me know if you find anything.

**Comment by emilm** [comment]
New session 67eb1e5e-db58-48f5-a6c6-e9411f7f3e80

Works! Thanks a lot!
