### ISSUE TITLE
Why PropertyConstraintException must be a checked Exception?

### ISSUE THREAD

**Issue by spyros87** [ChargeTimeEU/Java-OCA-OCPP#63]
Hello there,

I would like to ask you what is the reasoning for having the `PropertyConstraintException` to be a *checked* Exception. It's more similar to default Java `IllegalArgumentException` which is unchecked and it does not require special constructs to handle them.

Thank you in advance

**Comment by TVolden** [comment]
Hi Spyros

Thanks for your request. I haven't given it much thought, so there is no reason really.

I can change it, but I think you should make a PR with the change, so you get the credit. What do you say? 🙂

Thanks again

Thomas

**Comment by spyros87** [comment]
The PR is merged therefore I close the issue.

**Comment by TVolden** [comment]
Thanks for your help. I appreciate it.
