### ISSUE TITLE
DiagnosticsStatusNotification and FirmwareStatusNotification Requests currently assumed as Central System initiated, should be CP initiated

### ISSUE THREAD

**Issue by Cinazu** [ChargeTimeEU/Java-OCA-OCPP#64]
For Profile Firmware Management the messages DiagnosticsStatusNotification.req and FirmwareStatusNotification.req are currently assumed as initiated by the Central System instead of the Charge Point.

**Comment by TVolden** [comment]
Thanks for your issue. 

I'll get a chance to look at it tomorrow. Hope that's okay.

Thomas

**Comment by TVolden** [comment]
I committed a change that should fix this, please verify and close the issue if this fixed it.
Thanks again.

The SNAPSHOT is uploaded to maven central repo
