### ISSUE TITLE
why no ReserveNowRequestFeature?

### ISSUE THREAD

**Issue by yangzhengnan-le** [ChargeTimeEU/Java-OCA-OCPP#7]
why no ReserveNowRequestFeature?

**Comment by TVolden** [comment]
Hello there, and thanks for the question.
So referring to the OCPP specification version 1.6, the ReserveNow.req (chapter 6.37.) is part of the Reservation feature profile. - Currently I have only implemented the features for Core feature profile.

I have a epic for the Reservation feature profile, please see:
https://tree.taiga.io/project/tvolden-java-oca-ocpp/epic/23

I can notch it up, if you need it.

**Comment by yangzhengnan-le** [comment]
Thank you for your warm reply.I have already realize Reserve function, And what is your personal E-mail? Can we make frends?

**Comment by TVolden** [comment]
You are welcome to e-mail me at tv@chargetime.eu. :)

**Comment by TVolden** [comment]
This was added with #56
