### ISSUE TITLE
JSON DateTime parsing is too strict

### ISSUE THREAD

**Issue by JanLapp** [ChargeTimeEU/Java-OCA-OCPP#72]
JSONCommunicator.CalendarDeserializer only accepts DateTime strings with time zone ID given as 'Z', however I couldn't find anything in the 1.6 specs that requires this (UTC is merely recommended according to §3.13). Parsing the string with ZonedDateTime#parse should be fine.

**Comment by TVolden** [comment]
Hi @JanLapp

As far as I remember I locked the strict date format to solve a problem for someone. I can't really remember why.

Anyway, it's a good sugeestion. I think it should be changed right away... Unfortunately I'm on vacation, and don't have a computer handy, so can I get you to introduce the change as a PR?

Thomas

**Comment by JanLapp** [comment]
I have since learned that Java 8 ZonedDateTime has a bug and does not accept some time zone formats either: https://bugs.openjdk.java.net/browse/JDK-8032051 (fixed in Java 9) :(
Closing this now.
Best regards
