### ISSUE TITLE
Wrong notification handleStartTransactionRequest at the end of the transaction

### ISSUE THREAD

**Issue by sashoran** [ChargeTimeEU/Java-OCA-OCPP#74]
I am testing OCA OCPP with charging station Schnider EVlink 	EVB1A22P4KI.
Currently I am working with OCA OCPP revision ad6905e5bff853d45bdc76dbe8f9f62d69e01a1a.
Most of the already implemented features work surprisingly well. Congrats from me!

I only noticed the following bug:
When I start transaction, the station begins charging. I am receiving "Charging" on handleStatusNotificationRequest hook. So far so good.

When I stop the transaction (either by stop transaction command or just by unplugging the cable) I receive final handleStartTransactionRequest ?!?
Then after this notification I am receiving Available status.

My expectation is that at this moment I should reveive: handleStopTransactionRequest
And this is important for me, because stop notification contains meter ending value.
Instead start notification always gives mi 0 meter starting value.

Please check it this is a bug on your side.
It can also be an EVlink bug but to me it is barely possible.

BR,
Alexander Tzvetanov
Appladesign LLC

**Comment by TVolden** [comment]
Hi Alexander,

Thanks for your feedback, it's nice to hear that so much works out of the box.

The first thing that comes to mind, is the mapping, but it seems correct:
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/master/ocpp-v1_6/src/main/java/eu/chargetime/ocpp/feature/profile/ServerCoreProfile.java

What about the logs, what do they show?

**Comment by TVolden** [comment]
The features have the correct action names assigned.

Everything checks out on my end. So unless you have some log outputs, I can't figure out what could go wrong.

**Comment by sashoran** [comment]
Hi Tomas,
I was just looking at ServerCoreProfile.java
<https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/master/ocpp-v1_6/src/main/java/eu/chargetime/ocpp/feature/profile/ServerCoreProfile.java>
It looks correct to me. If you especially mentioned handleRequest.
Probably something in the request (parser) is wrong. Or just the CS sends a
wrong notification.
Currently I cannot see anything in its log.
I finally tested last Friday.
Right now I don't have a car to test with.

Next time I will dig in EVlink ligs (if they log anythig).

However, right now the fact is that I am receiving only Start notifications.

I wanted to have you checked for the issue. When I am certain that there is
no bug on your side I'll try to contact Schnider.

Thank you for the quick response.
/Alexander

**Comment by TVolden** [comment]
The parser uses the action-string to identify the class (I checked that in the feature profile). The event handler calls you based on which class was identified (I checked this mapping). My guess is that the CS sends a start transaction request or at least the action is set to "StartTransaction" (this should cause an exception).

**Comment by sashoran** [comment]
Thank you Thomas,
Can you help me, where I can put a break point, to catch the transaction
before parsing?
I want to intercept the root transaction (JSON) and if something is wrong
there, I will have proof to ask Schnider to check their CS behavior.
I am going to hire a car again and to make another tests until the end of
this week.

I am becoming more confident that something is wrong in CS side.

According to me the most important thing is to receive "end transaction"
notification because it contains EndMeter value.
I need this value if I want to implement "Pay now" feature.

Off topic:
By googling I found your project OCA OCPP and I was really inspired that
somebody took this work to implement OCPP for Java.
I am rally thankful that you do this job.
And I am going to use it ASAP if I win the project to implement billing
system for my potential customers.

Thank you again,
Alexander

**Comment by TVolden** [comment]
Hi Alexander,

The best place to debug the raw message would be here:
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/master/ocpp-common/src/main/java/eu/chargetime/ocpp/Communicator.java#L244

Thanks for your kind words. I must say that all the feedback and all the help I receive, really makes it worth the effort. 😃

Thomas

**Comment by sashoran** [comment]
Dear Thomas,
After a little research I found out that this issue is not a bug in the OCA OCPP framework.
You can close this issue as "not relevant".

About the messages start/stop charging: 
They come from the car. Not even from CS.
For example: eUP sends start charging message but does not send stop message.
Renault does not send neither start nor stop charging.
That is it.

Thank you for the assistance.
Alexander

**Comment by TVolden** [comment]
Hi Alexander,

Okay, thanks for your feedback.

Sincerely,
Thomas Volden
