### ISSUE TITLE
Creation of a TestSetup

### ISSUE THREAD

**Issue by baisudhir** [ChargeTimeEU/Java-OCA-OCPP#75]
Dear Thomas ,
Thanks for your great work.
I am new to JAVA and OCPP. I have gone through the readme.md file but not able to get enough information on how to run and create a test setup for client and server.Will you give some tips how to build and create a test setup for client and server.

Thanks and Regards,
Sudhir

**Comment by TVolden** [comment]
Hi Sudhir,

The integration tests are basically a test setup, that passes messages from client to server and vice versa.
Please see: 
https://github.com/ChargeTimeEU/Java-OCA-OCPP/tree/master/ocpp-v1_6-test

You can run the integration tests with the maven command: `mvn integration-test`

Please note that this project is a library to help people implement their charge boxes and central systems. You can't really 'run' it, since it's not an app.
If you are looking for a full central system, I'd recommend something like https://github.com/RWTH-i5-IDSG/steve

I hope it helps.

Sincerely
Thomas

**Comment by baisudhir** [comment]
Dear Thomas ,
Thanks for your valuable information.
I try to build "ocpp-common" and "ocpp-v1_6" module to generate jar but both build failed. A screenshot of the same is attached for your reference.
![build_error](https://user-images.githubusercontent.com/41739247/43600529-70131d90-96a8-11e8-8761-38d334d392b2.jpg)
Kindly guide me how to build these two module.It will be great help me to proceed to build a UI.

Thanks and Regards,
Sudhir

**Comment by TVolden** [comment]
Hi Sudhir,

From the screen shot you sent, I'd recommend that you go one folder up and type: `mvn install`

Thomas

**Comment by baisudhir** [comment]
Dear Thomas ,
Thanks for your prompt response.I tried to build with command mvn install but getting the following error( given in screenshot) for common module.
![error1](https://user-images.githubusercontent.com/41739247/43603709-635f9890-96b1-11e8-90bc-689d5f3a2d19.jpg)
![error1-1](https://user-images.githubusercontent.com/41739247/43603710-63949496-96b1-11e8-8370-9a309b5c965d.jpg)

Thanks and Regards,
Sudhir

**Comment by TVolden** [comment]
Oh right, the Java docs fails... How strange, I'll have to check that. Anyway, it looks like compile and test passes, which should be good enough.

**Comment by baisudhir** [comment]
Dear Thomas ,
when I skip Javadoc while building, (mvn -Dmaven.javadoc.skip=true verify) the common module is building but "ocpp-v1_6" module build is failed the error message is given below.
![error](https://user-images.githubusercontent.com/41739247/43604483-8251ed8c-96b3-11e8-8614-fa27b77c0071.jpg)

Thanks and Regards,
Sudhir

**Comment by baisudhir** [comment]
Dear Thomas ,
which version JDK is required? I am using jdk-9.0.1 version.
Thanks and Regards,
Sudhir

**Comment by TVolden** [comment]
Ah maybe that's it. It's written for 1.8

**Comment by baisudhir** [comment]
Dear Thomas ,
Thanks,I will install 1.8 and inform you the result.
Thanks and Regards,
Sudhir

**Comment by baisudhir** [comment]
Dear Thomas ,
Thanks for your support with jdk 1.8 it successfully builded .
Thanks and Regards,
Sudhir

**Comment by TVolden** [comment]
That's wonderful news. 😃
