### ISSUE TITLE
SetChargingProfile results in FormationValidation Error

### ISSUE THREAD

**Issue by dersteve** [ChargeTimeEU/Java-OCA-OCPP#78]
I'm trying to send a **SetChargingProfile** Command to the station via the lib, but I'm getting a **FormationValidation Error** back. It might be the stations problem or me/the lib sending a wrong message/part of the message. Anyone else seeing a similar issue?

I'm testing with a eBee station.

### Message sent to the station:
```
[
  2, 
  "faa4aaaf-5dad-482e-8353-6d5bc613e39e", 
  "SetChargingProfile", 
  {
    "chargingProfile": {
      "chargingProfileId": 0, 
      "chargingProfileKind": "Relative", 
      "chargingProfilePurpose": "TxProfile", 
      "chargingSchedule": {
        "chargingRateUnit": "A", 
        "chargingSchedulePeriod": [
          {
            "limit": 9.0, 
            "numberPhases": 3, 
            "startPeriod": 0
          }
        ]
      }, 
      "stackLevel": 0, 
      "transactionId": 2
    }, 
    "connectorId": 1
  }
]
```

### Response from the station:
```
[
  4, 
  "faa4aaaf-5dad-482e-8353-6d5bc613e39e", 
  "FormationViolation", 
  "Command parsing error", 
  {}
]
```

**Comment by TVolden** [comment]
Hi Steve,

I can try to check the message up against the OCPP specs. I know there's some rules to follow when it comes to the profile.

Thomas

**Comment by dersteve** [comment]
I checked it yesterday and was certain that the message has the right format, but we also tried this morning with a eLuminocity station and we get the same error back from this station. I'm starting to think that the message is wrong that we send :-) Maybe there is something that I overlook all the time. If you can check the message that would certainly help

**Comment by froehr** [comment]
Hi, I'm a colleague of @dersteve and just found that the library is sending the attribute name 'chargingProfile' in the SetChargingProfile.req while the Ocpp 1.6. documentation seems to expect it to be 'csChargingProfiles'. I would guess this is causing the error while parsing the request. Can you confirm this @TVolden?

**Comment by TVolden** [comment]
Hi @froehr 

I think you are spot on the money! I can even see that the Xml parser is instructed to call it csChargingProfiles:
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/master/ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/smartcharging/SetChargingProfileRequest.java#L90

Could it be as simple as to rename the field to getCsChargingProfiles/setCsChargingProfiles?

**Comment by TVolden** [comment]
Cool. The PR is accepted, thanks for your help. 

Please close the issue if it works. :)
