### ISSUE TITLE
Missing ClearChargingProfileRequest

### ISSUE THREAD

**Issue by AllRange1337** [ChargeTimeEU/Java-OCA-OCPP#81]
It seems the "ClearChargingProfileRequest" Class is missing

**Comment by TVolden** [comment]
Hi @AllRange1337

You're right, the smart charging feature is missing clear charging profile and set composite schedule.

I'll try to find some time in my schedule to look at it. But I'd also like to call out for a community hero, who would like to contribute.

Sincerely
Thomas

**Comment by dersteve** [comment]
@AllRange1337 are you working on adding it?

**Comment by froehr** [comment]
I guess clearing a charging profile is not implemented, yet. We will look into this during the next two weeks if nobody is actively working on it right now.

**Comment by nickomalley1** [comment]
I have had a look through the code and it looks like
ClearChargingProfileTask.java
GetChargingProfileTask.java
GetCompositeScheduleTask.java

have the basic  classes defined, but no further implementation has been added. 
I would like to help padding this out but i'm not a professional developer,  If someone is ok to guide me I will do the work to add the code.

regards
Nick

**Comment by froehr** [comment]
Hey, we'll need to finish it during the next days as its a blocker for a use case we have. So I'll start implementing it now. Sorry, its a bit urgent for our project.

**Comment by froehr** [comment]
Please check https://github.com/ChargeTimeEU/Java-OCA-OCPP/pull/85
