### ISSUE TITLE
Reestablishing connection results in error

### ISSUE THREAD

**Issue by erikvda** [ChargeTimeEU/Java-OCA-OCPP#88]
I'm currently writing software for a CP with JSON/websockets and it seems like something is going wrong when the connection drops and I try to reconnect and send a HeartBeatRequest after that.

When I notice a connection drop, it triggers the ClientEvents() callback connectionClosed() in JSONClient.connect(...)) (client.isClosed() still returns false after the event?!)

I try to connect again. All goes fine, except for when I try to send a HeartbeatRequest it crashes and continuously spits out this log message:

_Session:170 An internal error occurred and the receiver was not able to process the requested Action successfully_

Could you please tell me, if I'm doing something wrong here? What's should be the procedure to reconnect after a connection drops?

Thanks in advance

```
  OCPPClient(String address, ClientCoreProfile coreProfile) {
        this.address = address;
        this.core = coreProfile;

        client = new JSONClient(coreProfile);
    }

    void addFWProfile(ClientFirmwareManagementProfile profile){
        this.fwProfile = profile;
        client.addFeatureProfile(profile);
    }

    void connect() throws Exception {
        client.connect(address, new ClientEvents() {
            @Override
            public void connectionOpened() {
                connected = true;
                logger.info("connection opened");
            }

            @Override
            public void connectionClosed() {
                try {
                    connected = false;
                    logger.info("connection closed");
                } catch (Exception ex) {
                    logger.error(ex.getMessage());
                }
            }
        });
    }
```

**Comment by TVolden** [comment]
Hi @erikvda,

I love to hear from people who's using my lib. Thanks you for reaching out.

The behavior your describing, sounds pretty strange. I'll have to try to recreate it with a test.

What kind of server have you tested against? Have you verfied that the error doesn't originate from the server?

**Comment by erikvda** [comment]
Hi @TVolden,

After deeper investigation the root cause of the problem turned out to be the way the server was implemented. Thanks for you quick reply, and keep up the good work!

Erik
