### ISSUE TITLE
TriggerMessage?

### ISSUE THREAD

**Issue by emilm** [ChargeTimeEU/Java-OCA-OCPP#9]
I am unable to find the implementation of this. Work in progress? :) Would you like to have a pull request for this or do you prefer to do it yourself? (noting that the pull request I already submitted isn't accepted) :)

**Comment by TVolden** [comment]
I have split my project plan into profiles (defines in the OCPP 1.6 specs). I can see that TriggerMessage is part (and apparently the only one) of Remote Trigger feature profile.
https://tree.taiga.io/project/tvolden-java-oca-ocpp/epic/22

You are welcome to implement it if you need it, I can also notch it up in priority, but I still have this configuration task before core profile is done, done.

**Comment by emilm** [comment]
Gotcha!
