### ISSUE TITLE
Smart Charging profile

### ISSUE THREAD

**Issue by artado** [ChargeTimeEU/Java-OCA-OCPP#92]
Hello,

It is a great library, thank you for supporting it.
I would like to ask if there is a support for ClearChargingProfile & GetCompositeSchedule messages from the Smart Charging profile. I can see implementation of the SetChargingProfile message, but for the full implementation if the Smart Charging the two messages above would be very important.

Thanks

**Comment by TVolden** [comment]
Hi @artado

Thanks for your request. Why did you close it?

Sincerely
Thomas

**Comment by artado** [comment]
Hi @TVolden,

Thanks for your reply.
I believe it was added a couple of months ago and I have just missed it working on my local repo.
