### ISSUE TITLE
Client side request handling

### ISSUE THREAD

**Issue by ChaithanyaReddy2321** [ChargeTimeEU/Java-OCA-OCPP#99]
client can send requests and server can handle them. But the client is not handling requests from server?

**Comment by TVolden** [comment]
Hi, sorry for my slow reply.

I'm not sure what you are asking. The client handles requests somewhat the same as the server. 

Please see the guide for a client here:
https://github.com/ChargeTimeEU/Java-OCA-OCPP/wiki/Setting-up-v1.6-OCPP-J-client

Can you give me a concrete example of your problem?

**Comment by TVolden** [comment]
Are you still having trouble @ChaithanyaReddy2321? - Hopefully not.
I'm closing the issue, but please don't hesitate to reopen if you disagree.
